### ISSUE TITLE
Update TTT with aka.ms powerpoint link

### ISSUE THREAD

**Issue by cole-g-johnson** [microsoft/aitour-preparing-for-ai-workloads#7]
Please update the TTT powerpoint link to be the aka.ms short link here:
https://github.com/microsoft/aitour-preparing-for-ai-workloads/tree/main/train-the-trainer#file-summary

For questions, you can reference [BRK471's repo](https://github.com/microsoft/aitour-leveraging-ai-for-infrastructure-management) which used the aka.ms link.

**Comment by cmtal** [comment]
Updated.
